### ISSUE TITLE
您好，我想请教一下这个IP问题

### ISSUE THREAD

**Issue by Haitai-92** [sodaling/redis-cluster-docker#1]
redis-server --slaveof 192.168.0.107 6379 --port 6380 --requirepass 1234 --masterauth 1234
请问一下这个192.168.0.107这个IP能告诉我是怎么来的么，而且我直接本地运行时，居然主从已经可以了，但是我本地CentOS的IP是192.168.230.131

**Comment by sodaling** [comment]
这我的问题,应该注明一下的.这ip是本地(不是容器里面)的ip,我直接ifconfig查出来的.
你确定能主从可以么?不是单单docker-compose up -d 就可以了喔.你看看docker log,看看几个(无论主从)的log信息,看看这几个redis实例的log是否有报错.同时你试一下主redis进行set等操作后,从redis有没有读到信息
